site_name: 'TB-Profiler'
docs_dir: '../../docs/pt'                  
site_dir: '../../build/pt'                 

repo_url: https://github.com/jodyphelan/TBProfiler

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  
theme:
  name: material
  language: pt
extra:
  alternate:
    - name: English
      link: https://jodyphelan.github.io/TBProfiler/en/
      lang: en
    - name: Português
      link: https://jodyphelan.github.io/TBProfiler/pt/
      lang: pt
    - name: Français
      link: https://jodyphelan.github.io/TBProfiler/fr/
      lang: fr